### ISSUE TITLE
How to launch the JavaFX version?

### ISSUE THREAD

**Issue by scharf** [sibvisions/jvx.kitchensink#5]
When I launch `JVx KitchenSink (JavaFX).launch` it looks exactly the same as the swing version. My guess is that the JavaFX driver does not get loaded properly...

**Comment by scharf** [comment]
Ah, the exception is silently catched and the swing loader is used https://github.com/sibvisions/jvx.kitchensink/blob/17f0a6e07f223860e24b19ab661072033e0c07f5/src/com/sibvisions/kitchensink/Main.java#L61

```
java.lang.ClassNotFoundException: com.sibvisions.rad.ui.javafx.impl.FXFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.sibvisions.kitchensink.Main.main(Main.java:54)
```

**Comment by RobertZenz** [comment]
You're right, about both.

The exception should at least be logged as a warning, I'll add that.

There is no JVxFX.jar included in the project, I believe that that was done for convenience reasons at the time. I will simply add the latest release version so that the launcher works as expected out of the box.

**Comment by RobertZenz** [comment]
I just pushed the needed changes, can you verify that you can now use the JavaFX launcher without issues?

**Comment by scharf** [comment]
👍 works really nicely out of the box!
